services:
  database:
    image: mariadb:latest
    container_name: IMDB_DB
    environment:
      MYSQL_ROOT_PASSWORD: {{SECRET_DB_ROOTPASSWORD}}
    volumes:
      - imdb_db_storage:/var/lib/mysql
      - ./SQL/DB_Setup.sql:/docker-entrypoint-initdb.d/DB_Setup.sql
    ports:
      - "3306:3306"
    networks:
      - IMDB_DockerNetwork

  db-ui:
    image: phpmyadmin/phpmyadmin
    container_name: IMDB_DB_GUI
    environment:
      PMA_HOST: IMDB_DB
      PMA_PORT: 3306
      PMA_USER: imdb_admin
      PMA_PASSWORD: {{SECRET_DB_PASSWORD}}
    ports:
      - "4080:80"
    volumes:
      - ./config.inc.php:/etc/phpmyadmin/config.inc.php
    networks:
      - IMDB_DockerNetwork
    depends_on:
      - database

networks:
  IMDB_DockerNetwork:
    driver: bridge

volumes:
  imdb_db_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:/IMDB_SQL/sql
